import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function GameAnalytics() {
  const router = useRouter();
  const { game_id } = router.query;

  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  const SESSION_LIMIT = 100;

  // ================= LOAD DATA =================
  useEffect(() => {
    if (!game_id) return;

    const load = async () => {
      try {
        const res = await fetch(
          `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/analytics/game/${game_id}`
        );
        const json = await res.json();
        if (!res.ok) throw new Error(json.error || "Failed to load analytics");
        setData(json);
      } catch (e) {
        setError(e.message);
      } finally {
        setLoading(false);
      }
    };

    load();
  }, [game_id]);

  if (loading) return <p style={page}>Analyzing player behavior…</p>;
  if (error) return <p style={{ ...page, color: "red" }}>{error}</p>;

  // ================= DERIVED METRICS =================
  const used = data.total_sessions || 0;
  const usagePercent = Math.min(
    100,
    Math.round((used / SESSION_LIMIT) * 100)
  );

  const usageColor =
    usagePercent >= 90
      ? "#dc2626"
      : usagePercent >= 70
      ? "#d97706"
      : "#16a34a";

  const decisionColor =
    data.health === "GO"
      ? "#16a34a"
      : data.health === "KILL"
      ? "#dc2626"
      : "#d97706";

  let confidence = "Low";
  if (data.total_sessions >= 20) confidence = "Medium";
  if (data.total_sessions >= 50) confidence = "High";

  // ================= RECOMMENDATIONS =================
  const fixes = [];
  if (data.health === "ITERATE") {
    fixes.push("Simplify onboarding and early gameplay");
    fixes.push("Reduce difficulty spikes in first sessions");
  }
  if (data.health === "KILL") {
    fixes.push("Stop development to avoid sunk cost");
    fixes.push("Rethink core loop or target audience");
  }
  if (data.health === "GO") {
    fixes.push("Increase sample size for confidence");
    fixes.push("Start retention & monetization experiments");
  }

  // ================= REPORT TEXT =================
  const reportText = `
LaunchSense Decision Report
---------------------------

Game ID: ${game_id}

FINAL DECISION: ${data.health}
Confidence: ${confidence}

Total Sessions: ${data.total_sessions}
Average Risk: ${data.average_risk}

Decision Breakdown:
GO: ${data.go_percent}%
ITERATE: ${data.iterate_percent}%
KILL: ${data.kill_percent}%

Recommended Actions:
${fixes.map((f) => "- " + f).join("\n")}

Generated by LaunchSense
  `.trim();

  const copyReport = async () => {
    await navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // ================= UI =================
  return (
    <div style={page}>
      <h1>Game Decision Report</h1>
      <p style={{ color: "#666" }}>
        Game ID: <code>{game_id}</code>
      </p>

      {/* SESSION USAGE */}
      <div style={card}>
        <strong>Session Usage (Free Plan)</strong>
        <p style={{ color: usageColor }}>
          {used}/{SESSION_LIMIT} sessions used ({usagePercent}%)
        </p>
        {usagePercent >= 70 && (
          <p style={{ color: usageColor }}>
            ⚠ You’re nearing your free limit.
            {usagePercent >= 100 && (
              <>
                {" "}
                <a href="/pricing" style={{ color: "#000" }}>
                  Upgrade to continue analysis →
                </a>
              </>
            )}
          </p>
        )}
      </div>

      {/* FINAL DECISION */}
      <div style={{ ...card, border: `3px solid ${decisionColor}` }}>
        <h2 style={{ color: decisionColor }}>
          FINAL DECISION: {data.health}
        </h2>
        <p>
          Confidence: <strong>{confidence}</strong>
        </p>
      </div>

      {/* METRICS */}
      <div style={card}>
        <h3>Metrics</h3>
        <p>Total Sessions: {data.total_sessions}</p>
        <p>Average Risk Score: {data.average_risk}</p>
        <p>GO: {data.go_percent}%</p>
        <p>ITERATE: {data.iterate_percent}%</p>
        <p>KILL: {data.kill_percent}%</p>
      </div>

      {/* RECOMMENDATIONS */}
      <div style={card}>
        <h3>Recommended Next Actions</h3>
        <ul>
          {fixes.map((f, i) => (
            <li key={i}>{f}</li>
          ))}
        </ul>
      </div>

      {/* COPY REPORT */}
      <div style={{ marginTop: 30 }}>
        <button onClick={copyReport} style={primaryBtn}>
          Copy Decision Report
        </button>
        {copied && (
          <span style={{ marginLeft: 10, color: "green" }}>✓ Copied</span>
        )}
      </div>

      {/* BACK */}
      <button onClick={() => router.push("/dashboard")} style={backBtn}>
        ← Back to Dashboard
      </button>
    </div>
  );
}

// ================= STYLES =================
const page = {
  padding: 40,
  maxWidth: 900,
};

const card = {
  marginTop: 24,
  padding: 20,
  border: "1px solid #ddd",
  borderRadius: 12,
  background: "#fafafa",
};

const primaryBtn = {
  padding: "10px 16px",
  background: "#000",
  color: "#fff",
  border: "none",
  cursor: "pointer",
};

const backBtn = {
  marginTop: 20,
  padding: "10px 16px",
  background: "#eee",
  border: "1px solid #ccc",
  cursor: "pointer",
};
