import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function GameAnalytics() {
  const router = useRouter();
  const { game_id } = router.query;

  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!game_id) return;

    fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL}/api/analytics/game/${game_id}`)
      .then((res) => res.json())
      .then((json) => {
        setData(json);
        setLoading(false);
      })
      .catch(() => {
        setError("Failed to load analytics");
        setLoading(false);
      });
  }, [game_id]);

  if (loading) return <p style={page}>Analyzing player behavior…</p>;
  if (error) return <p style={{ ...page, color: "red" }}>{error}</p>;

  const decisionColor =
    data.health === "GO"
      ? "#16a34a"
      : data.health === "KILL"
      ? "#dc2626"
      : "#d97706";

  // CONFIDENCE
  let confidence = "Low";
  if (data.total_sessions >= 20) confidence = "Medium";
  if (data.total_sessions >= 50) confidence = "High";

  // FIX SUGGESTIONS
  const fixes = [];
  if (data.health === "ITERATE") {
    fixes.push("Simplify onboarding and early gameplay.");
    fixes.push("Reduce difficulty spikes in early sessions.");
  }
  if (data.health === "KILL") {
    fixes.push("Stop development to avoid sunk cost.");
    fixes.push("Pivot or rethink core concept.");
  }
  if (data.health === "GO") {
    fixes.push("Increase sample size.");
    fixes.push("Test retention and monetization.");
  }

  // REPORT TEXT
  const reportText = `
LaunchSense Decision Report
--------------------------
Game ID: ${game_id}

FINAL DECISION: ${data.health}
Confidence Level: ${confidence}

Total Sessions: ${data.total_sessions}
Average Risk Score: ${data.average_risk}/100

Decision Breakdown:
- GO: ${data.go_percent}%
- ITERATE: ${data.iterate_percent}%
- KILL: ${data.kill_percent}%

Recommended Next Actions:
${fixes.map((f) => `- ${f}`).join("\n")}

Generated by LaunchSense
`;

  const copyReport = async () => {
    await navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div style={page}>
      <h1>Game Decision Report</h1>
      <p style={{ color: "#666" }}>
        Game ID: <code>{game_id}</code>
      </p>

      {/* FINAL DECISION */}
      <div
        style={{
          border: `3px solid ${decisionColor}`,
          padding: 24,
          borderRadius: 12,
          marginTop: 30,
        }}
      >
        <h2 style={{ color: decisionColor }}>
          FINAL DECISION: {data.health}
        </h2>
        <p style={{ fontSize: 18 }}>
          Confidence: <strong>{confidence}</strong>
        </p>
      </div>

      {/* ACTIONS */}
      <div
        style={{
          marginTop: 24,
          padding: 20,
          border: "1px solid #ddd",
          borderRadius: 10,
        }}
      >
        <h3>Recommended Next Actions</h3>
        <ul>
          {fixes.map((f, i) => (
            <li key={i}>{f}</li>
          ))}
        </ul>
      </div>

      {/* EXPORT */}
      <div style={{ marginTop: 30 }}>
        <button onClick={copyReport} style={primaryBtn}>
          Copy Decision Report
        </button>
        {copied && <span style={{ marginLeft: 10 }}>✅ Copied</span>}
      </div>

      <button onClick={() => router.push("/dashboard")} style={backBtn}>
        ← Back to Dashboard
      </button>
    </div>
  );
}

const page = {
  padding: 40,
  maxWidth: 900,
};

const primaryBtn = {
  padding: "10px 16px",
  background: "#000",
  color: "#fff",
  border: "none",
  cursor: "pointer",
};

const backBtn = {
  marginTop: 30,
  padding: "10px 16px",
  background: "#eee",
  border: "none",
  cursor: "pointer",
};
